---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: false
---

## Loading and preprocessing the data
```{r load_data, results = "hide"}
if (!dir.exists("data")) {
    dir.create("data")
}
unzip("activity.zip", exdir = "data")

activity_data <- read.csv("data/activity.csv")

library(dplyr)
library(ggplot2)
library(xtable)
```

## Histogram of total number of steps taken in a day
```{r total_steps_per_day_histogram, fig.keep="all", fig.show="asis"}
activity_summary <- activity_data %>%
    mutate_if(is.factor, as.Date) %>%
    group_by(date) %>%
    filter(!is.na(steps)) %>%
    summarise(total_steps = sum(steps))

print(qplot(activity_summary$total_steps,
    geom = "histogram",
    bins = nrow(activity_summary),
    xlab = "Total Steps",
    ylab = "Count",
    col = I("red"),
    fill = I("green")))
```

## What is mean and median of the total number of steps taken per day?
```{r total_steps_mean, results = "asis"}
steps_table <- as.data.frame(activity_data %>%
    mutate_if(is.factor, as.character) %>%
    group_by(date) %>%
    filter(!is.na(steps)) %>%
    summarise(mean_steps = mean(steps),
		median_steps = median(steps)) %>%
	select(Date = date, Mean = mean_steps, Median = median_steps))

xt <- xtable(steps_table,
    align = "llrr",
    digits = xdigits(steps_table),
	display = xdisplay(steps_table))

print(xt,
	type = "html",
    include.rownames = FALSE)
```

## What is the average daily activity pattern?
```{r average_daily_activity, results = "asis"}
activity_pattern <- activity_data %>%
    mutate_if(is.factor, as.character) %>%
    group_by(interval) %>%
    summarise(average_steps = mean(steps, na.rm = TRUE))

pattern_plot <- ggplot(data = activity_pattern, mapping = aes(interval, average_steps)) +
    geom_smooth(method = "lm", se = FALSE) +
	theme_linedraw(base_size = 14) +
    xlab("Interval (5 min)") +
    ylab("Average Steps")
print(pattern_plot)
```

## Imputing missing values
```{r handle_missing_values}
missing_data <- activity_data[is.na(activity_data$steps),]
missing_values <- count(missing_data)

imputed_values <- activity_data %>%
    group_by(date) %>%
	summarise(average_steps = mean(steps, na.rm = TRUE))
```

####There are `r missing_values` missing values.

## Are there differences in activity patterns between weekdays and weekends?
